eeewbs_base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from eeewbs_base.teacher import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'teachers', views.TeacherViewSet)
router.register(r'student', views.StudentViewSet)
router.register(r'project', views.ProjectViewSet)
router.register(r'specialization', views.SpecializationViewSet)
router.register(r'course', views.CourseViewSet)


# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('magic_number/', include('magic_number.urls')),
    path('admin/', admin.site.urls),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

magic_number/urls.py
from django.urls import path

from . import views

app_name = 'magic_number'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
]

magic_number/models.py
from django.db import models
from django.utils.safestring import mark_safe


class Question(models.Model):
    question_text = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')
    banner = models.ImageField(upload_to="magic_number/static/magic_number")

    def __str__(self):
        return self.question_text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    birthday_input = models.DateTimeField('birthday')
    avatar = models.IntegerField(default=0)

    def __str__(self):
        return self.birthday_input

magic_number/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Question
from random import randint

celebrities = {
    'Sheryl Sandberg': {
        'name': 'Sheryl Sandberg',
        'title': 'Facebook 首席运营官',
        'img': 'sandberg.jpg',
        'life': 5,
        'talent1': 4,
        'talent2': 1
    },
    'Gina Hope Rinehart': {
        'name': 'Gina Hope Rinehart',
        'title': '澳大利亚矿业大亨 - 汉考克探矿',
        'img': 'gina.jpg',
        'life': 3,
        'talent1': 3
    },
    'Abigail Johnson': {
        'name': 'Abigail Johnson',
        'title': '美国金融界最有实力的女性',
        'img': 'abigail.jpg',
        'life': 3,
        'talent1': 3
    },
    'Laurene Powell': {
        'name': 'Laurene Powell',
        'title': '爱默生基金会 创始人&主席',
        'img': 'laurene.jpg',
        'life': 9,
        'talent1': 2,
        'talent2': 7
    },
    'Susanne Klatten': {
        'name': 'Susanne Klatten',
        'title': '藏在幕后的女决策者 阿尔塔纳&宝马汽车',
        'img': 'susanne.jpg',
        'life': 5,
        'talent1': 3,
        'talent2': 2
    },
    'Jacqueline Mars': {
        'name': 'Jacqueline Mars',
        'title': '知名糖果巨头玛氏公司的女继承人',
        'img': 'jacqueline.jpg',
        'life': 6,
        'talent1': 2,
        'talent2': 4
    },
    '杨惠妍': {
        'name': '杨惠妍',
        'title': '碧桂园董事局 副主席',
        'img': 'yanghuiyan.jpg',
        'life': 1,
        'talent1': 2,
        'talent2': 8
    },
    'Alice Walton': {
        'name': 'Alice Walton',
        'title': '沃尔玛创始人山姆·沃尔顿长女',
        'img': 'alice.jpg',
        'life': 4,
        'talent1': 3,
        'talent2': 1
    },
    '张欣': {
        'name': '张欣',
        'title': 'SOHO中国首席执行官、联合创始人',
        'img': 'zhangxin.jpg',
        'life': 8,
        'talent1': 3,
        'talent2': 5
    },
    '史晓燕': {
        'name': '史晓燕',
        'title': '北京伊力诺依投资有限公司法人&董事长',
        'img': 'shixiaoyan.jpg',
        'life': 11,
        'talent1': 2,
        'talent2': 9
    },
    '林晓芸': {
        'name': '林晓芸',
        'title': '中鑫金业集团董事局主席&董事长',
        'img': 'linxiaoyun.jpg',
        'life': 5,
        'talent1': 4,
        'talent2': 1
    },
    '潘楚颖': {
        'name': '潘楚颖',
        'title': 'PYE品牌首席品牌官，溢达集团中国零售部',
        'img': 'panchuyin.jpg',
        'life': 7,
        'talent1': 4,
        'talent2': 3
    },
    '宗馥莉': {
        'name': '宗馥莉',
        'title': '宏胜饮料集团总裁、浙江省商会副会长',
        'img': 'zongfuli.jpg',
        'life': 9,
        'talent1': 2,
        'talent2': 7
    },
    '董明珠': {
        'name': '董明珠',
        'title': '珠海格力电器电器股份有限公司董事长',
        'img': 'dongmingzhu.jpg',
        'life': 3,
        'talent1': 3
    },
    '杨澜': {
        'name': '杨澜',
        'title': '阳光文化影视公司董事局主席',
        'img': 'yanglan.jpg',
        'life': 4,
        'talent1': 3,
        'talent2': 1
    },
    '翟美卿': {
        'name': '翟美卿',
        'title': '香港集团有限公司总裁',
        'img': 'cuimeiqin.jpg',
        'life': 9,
        'talent1': 2,
        'talent2': 7
    },
    '张玉珊': {
        'name': '张玉珊',
        'title': '修身堂控股有限公司主席',
        'img': 'zhangyushan.jpg',
        'life': 4,
        'talent1': 3,
        'talent2': 1
    },
    '陈金霞': {
        'name': '陈金霞',
        'title': '上海汇能投资管理公司执行董事',
        'img': 'chenjinxia.jpg',
        'life': 1,
        'talent1': 3,
        'talent2': 7
    },
    '尹索微': {
        'name': '尹索微',
        'title': '重庆力帆集团董事',
        'img': 'yisuowei.jpg',
        'life': 5,
        'talent1': 1,
        'talent2': 4
    },
    '董思阳': {
        'name': '董思阳',
        'title': '上海金柯天烨股权投资管理有限公司总裁',
        'img': 'dongsiyang.jpg',
        'life': 6,
        'talent1': 3,
        'talent2': 3
    },
    '张馨之': {
        'name': '张馨之',
        'title': '来福掌柜创始人',
        'img': 'zhangxinzhi.jpg',
        'life': 5,
        'talent1': 3,
        'talent2': 2
    },
    '尹峰': {
        'name': '尹峰',
        'title': '香港国际翼咖啡美食传播有限公司董事',
        'img': 'yifeng.jpg',
        'life': 5,
        'talent1': 3,
        'talent2': 2
    },
    '杨思维': {
        'name': '杨思维',
        'title': '壹心娱乐创始合伙人',
        'img': 'yangsiwei.jpg',
        'life': 9,
        'talent1': 2,
        'talent2': 7
    },
    '李静': {
        'name': '李静',
        'title': '乐蜂网创始人',
        'img': 'lijing.jpg',
        'life': 9,
        'talent1': 2,
        'talent2': 7
    },
    '张兰': {
        'name': '张兰',
        'title': '俏江南集团董事长',
        'img': 'zhanglan.jpg',
        'life': 7,
        'talent1': 3,
        'talent2': 4
    },
    '何超琼': {
        'name': '何超琼',
        'title': '美高梅中国主席、信德集团行政主席兼董事总经理',
        'img': 'hechaoqiong.jpg',
        'life': 7,
        'talent1': 3,
        'talent2': 4
    },
}


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')
    context = {
        'latest_question_list': latest_question_list
    }
    return render(request, 'magic_number/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'magic_number/details.html', {'question': question})


def results(request, question_id):
    birthday, name = request.POST['birthday'], request.POST['name']
    birthday = birthday.replace('-', '')
    life_number, talent_number1, talent_number2 = get_magic_number_sum(birthday)
    celebrity = get_right_celebrity(life_number)
    if not celebrity:
        celebrity = celebrities["张欣"]

    cele_talent_1, cele_talent_2 = get_cele_talent(celebrity)
    talent_number1, talent_number2 = get_talent_numbers(cele_talent_1, cele_talent_2,
                                                        talent_number1, talent_number2)
    similarity = get_similarity(talent_number1, talent_number2)
    context = {
        'life_number': life_number,
        'talent_number1': talent_number1,
        'talent_number2': talent_number2,
        'name': name,
        'cele_name': celebrity['name'],
        'pic_name': celebrity['img'],
        'desc': celebrity['title'],
        'similarity': similarity}
    return render(request, 'magic_number/result.html', context)


def get_cele_talent(celebrity):
    cele_talent_1 = celebrity['talent1']
    cele_talent_2 = celebrity['talent2'] if 'talent2' in celebrity.keys() else -1
    return cele_talent_1, cele_talent_2


def get_talent_numbers(cele_talent_1, cele_talent_2, talent_number1, talent_number2):
    if talent_number1 != cele_talent_1 and talent_number1 != cele_talent_2:
        talent_number1 = None
    if talent_number2 != cele_talent_1 and talent_number2 != cele_talent_2:
        talent_number2 = None
    if talent_number2 and not talent_number1:
        talent_number1, talent_number2 = talent_number2, None
    return talent_number1, talent_number2


def get_similarity(talent_number1, talent_number2):
    similarity = 50
    if talent_number1:
        similarity += 25
    if talent_number2:
        similarity += 25
    return similarity


def get_magic_number_sum(input_birthday):
    temp_sum = sum(int(i) for i in input_birthday)
    if temp_sum in [11, 22, 33]:
        return temp_sum, str(temp_sum)[0], str(temp_sum)[1]
    talent_number1, talent_number2 = str(temp_sum)[0], str(temp_sum)[1]
    return sum(int(i) for i in str(temp_sum)), int(talent_number1), int(talent_number2)


def get_right_celebrity(life_number, talent_number1=-1, talent_number2=-1):
    cele_temp_list = []
    for key, item in celebrities.items():
        if item['life'] == life_number:
            cele_temp_list.append(item)

    length = len(cele_temp_list)
    return cele_temp_list[randint(0, length - 1)] if length > 0 else None

magic_number/templates/magic_number/details.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <title></title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'magic_number/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'magic_number:results' question.id %}" method="post">
        {% csrf_token %}
        <label for="birthday">请输入你的生日</label>
        <input type="date" name="birthday" id="birthday" alt="你的生日" required>
        <br>
        <label for="name">请输入你的姓名</label>
        <input type="text" placeholder="请输入你的姓名" name='name' id="name" required>
        <br>
        {#    <input alt="头像" id="avatar" name="avatar" placeholder="请上传头像" type="file" accept="file_extension|image/jpeg|image/jpg">#}
        <input class="btn btn-primary btn-lg" type="submit" value="提交">
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

magic_number/templates/magic_number/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'magic_number/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'magic_number:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

magic_number/templates/magic_number/result.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <title>结果</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'magic_number/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body class="h-100">
<div class="container text-center" style="height: 80%; color: aliceblue;">
    <div>
        <h4>快来测一测，看看谁是和你</h4>
        <h3><i class="golden_font">100%</i>相似的女富豪</h3>
    </div>
    <br>
    <section id="result">
        <div class="row">
            <div class="col-4">
                <img src="{% static  'magic_number/' %}{{ pic_name }}" alt="Image">

            </div>
            <div class="col-4">
            </div>
            <div class="col-4">
                <img src="{% static 'magic_number/sushi.png' %}" alt="Image">
            </div>
        </div>
        <div class="row align-items-center">
            <div class="col-4">
                <h4 class="golden_font">{{ cele_name }}</h4>
            </div>
            <div class="col-4">
                <h3 class="golden_font">VS</h3>
            </div>
            <div class="col-4">
                <h4 class="golden_font">{{ name }}</h4>
            </div>
        </div>
        <div class="row align-items-center">
            <div class="col-4">
                <h6>{{ desc }}</h6>
            </div>
            <div class="col-4">
                <h5>相似度</h5>
                <h5 class="golden_font">{{ similarity }}%</h5>
            </div>
            <div class="col-4">
            </div>
        </div>
        <div class="row align-items-center">
            <div class="col">
                <h4>
                    生命数字同为：<i class="golden_font">{{ life_number }}</i>
                </h4>
                {% if talent_number1 %}
                    <h4>
                        天赋数字同为：<i class="golden_font">{{ talent_number1 }}</i>
                        {% if talent_number2 %}
                            和
                            <i class="golden_font">{{ talent_number2 }}</i>
                        {% endif %}
                    </h4>
                {% endif %}
            </div>
        </div>
    </section>
</div>

<footer class="footer container-fluid">
    <div class="row" style="height: 100%">
        <div class="col-7 align-self-center">
            <h4 style="text-align: center">梦想还是要有的 <br> 万一实现了呢</h4>
        </div>
        <div class="col-5 align-self-center">
            <img src="../../static/magic_number/sushi.png" alt="qrcode">
        </div>
    </div>

</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>